version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clinic_frontend
    restart: always
    ports:
      - "8080:80"
    networks:
      - clinic_dashboard

networks:
  clinic_dashboard:
    driver: bridge