version: "3.9"

services:
  gclinico:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dashboard-gclinico
    restart: always
    expose:
      - "5173"
    networks:
      - sarah-network

networks:
  sarah-network:
    external: true