server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location /gclinico/ {
        try_files $uri $uri/ /gclinico/index.html;
    }

    location = {
        return 302 /gclinico/;
    }
}